server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: task-management-api

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:taskdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console

# Logging Configuration
logging:
  level:
    com.cloudnova: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always